require: rubocop-rspec

inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.3
  DisplayCopNames: true
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'db/**/*'
    - 'script/**/*'
    - 'vendor/**/*'

Metrics/LineLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

# catalog_controller.rb is usually long because it is mostly configuration
# user.rb could use some refactoring, see #249
Metrics/ClassLength:
  Exclude:
    - 'app/models/user.rb'
    - 'app/controllers/catalog_controller.rb'

Metrics/CyclomaticComplexity:
  Exclude:
    - 'spec/support/helpers/generic_files.rb'
    - 'spec/features/static_pages_spec.rb'
    - 'app/models/generic_file.rb'
    - 'app/helpers/catalog_helper.rb'

Metrics/PerceivedComplexity:
  Exclude:
    - 'spec/support/helpers/generic_files.rb'
    - 'spec/features/static_pages_spec.rb'
    - 'app/models/generic_file.rb'
    - 'app/helpers/catalog_helper.rb'

Style/BlockDelimiters:
  Exclude:
    - 'spec/**/*'

Style/BlockEndNewline:
  Exclude:
    - 'spec/**/*'

Style/MultilineBlockLayout:
  Exclude:
    - 'spec/**/*'

Style/IndentationConsistency:
  EnforcedStyle: rails

Style/CollectionMethods:
  PreferredMethods:
    collect: 'map'
    collect!: 'map!'
    inject: 'reduce'
    detect: 'find'
    find_all: 'select'

Style/WordArray:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/SingleLineBlockParams:
  Enabled: false

Style/SignalException:
  Enabled: false

Style/ClassVars:
  Exclude:
    - 'spec/support/user_login.rb'
    - 'spec/support/authentication.rb'

Style/GlobalVars:
  Exclude:
    - 'spec/features/support/feature_cleanup.rb'
    - 'spec/features/static_pages_spec.rb'
    - 'config/initializers/redis_config.rb'
    - 'config/initializers/active_record_base_redis.rb'
    - 'config/initializers/active_fedora_base_redis.rb'
    - 'config/environment.rb'

Style/VariableName:
  Exclude:
    - 'lib/share_notify/push_document.rb'

Style/BracesAroundHashParameters:
  Exclude:
    - 'config/deploy.rb'

Style/AccessorMethodName:
  Exclude:
    - 'config/application.rb'

Style/PredicateName:
  Exclude:
    - 'app/controllers/application_controller.rb'

# Causes spec/views/catalog/_index_default.html.erb_spec.rb:20 to fail because Blacklight is enforcing the
# encoding of a frozen string:
# RuntimeError:
#   can't modify frozen String
#   /Users/awead/.gem/ruby/2.3.0/gems/blacklight-5.17.2/app/presenters/blacklight/document_presenter.rb:85:in `force_encoding'
Style/FrozenStringLiteralComment:
  Exclude:
    - 'spec/views/catalog/_index_default.html.erb_spec.rb'

Lint/UselessAssignment:
  Exclude:
    - 'config/compass.rb'

Lint/LiteralInCondition:
  Exclude:
    - 'spec/support/user_no_ldap.rb'

Rails:
  Enabled: true

Rails/Date:
  Enabled: false

Rails/TimeZone:
  Enabled: false

RSpec/ExampleWording:
  CustomTransform:
    be: is
    have: has
    not: does not
    NOT: does NOT
  IgnoredWords:
    - only

RSpec/FilePath:
  Enabled: false

RSpec/InstanceVariable:
  Enabled: false

RSpec/DescribeClass:
  Exclude:
    - 'spec/views/**/*'
    - 'spec/routing/**/*'
    - 'spec/rake/**/*'
    - 'spec/config/**/*'
    - 'spec/models/batch_spec.rb'
    - 'spec/features/**/*'
