inherit_gem:
  niftany: niftany_rubocop.yml

inherit_from:
  - .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - 'fits/**/*'
    - 'db/**/*'
    - 'script/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'bin/**/*'

# catalog_controller.rb is usually long because it is mostly configuration
# user.rb could use some refactoring, see #249
Metrics/ClassLength:
  Exclude:
    - 'app/models/user.rb'
    - 'app/controllers/catalog_controller.rb'
    - 'app/services/external_files_conversion.rb'

Metrics/CyclomaticComplexity:
  Exclude:
    - 'spec/support/helpers/generic_files.rb'
    - 'spec/features/static_pages_spec.rb'
    - 'app/models/generic_file.rb'
    - 'app/helpers/catalog_helper.rb'

Metrics/PerceivedComplexity:
  Exclude:
    - 'spec/support/helpers/generic_files.rb'
    - 'spec/features/static_pages_spec.rb'
    - 'app/models/generic_file.rb'
    - 'app/helpers/catalog_helper.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/features/dashboard/dashboard_works_spec.rb'

Style/ClassVars:
  Exclude:
    - 'spec/support/user_login.rb'
    - 'spec/support/authentication.rb'

Style/GlobalVars:
  Exclude:
    - 'spec/features/support/feature_cleanup.rb'
    - 'spec/features/static_pages_spec.rb'
    - 'config/initializers/redis_config.rb'
    - 'config/initializers/active_record_base_redis.rb'
    - 'config/initializers/active_fedora_base_redis.rb'
    - 'config/environment.rb'

Naming/VariableName:
  Exclude:
    - 'lib/share_notify/push_document.rb'

Style/BracesAroundHashParameters:
  Exclude:
    - 'config/deploy.rb'

Naming/AccessorMethodName:
  Exclude:
    - 'config/application.rb'

Naming/PredicateName:
  Exclude:
    - 'app/controllers/application_controller.rb'

Naming/UncommunicativeMethodParamName:
  AllowedNames:
    - _
    - id
    - io

# Causes spec/views/catalog/_index_default.html.erb_spec.rb:20 to fail because Blacklight is enforcing the
# encoding of a frozen string:
# RuntimeError:
#   can't modify frozen String
#   /Users/awead/.gem/ruby/2.3.0/gems/blacklight-5.17.2/app/presenters/blacklight/document_presenter.rb:85:in `force_encoding'
Style/FrozenStringLiteralComment:
  Exclude:
    - 'spec/views/catalog/_index_default.html.erb_spec.rb'

Lint/UselessAssignment:
  Exclude:
    - 'config/compass.rb'

Lint/LiteralAsCondition:
  Exclude:
    - 'spec/support/user_no_ldap.rb'

RSpec/DescribeClass:
  Exclude:
    - 'spec/views/**/*'
    - 'spec/routing/**/*'
    - 'spec/rake/**/*'
    - 'spec/config/**/*'
    - 'spec/models/batch_spec.rb'
    - 'spec/features/**/*'
    - 'spec/support/**/*'
    - 'benchmark/spec/**/*'

RSpec/LetSetup:
  Enabled: false
