require: rubocop-rspec

# Offense count: 3
# Cop supports --auto-correct.
# Configuration parameters: Include, TreatCommentsAsGroupSeparators.
# Include: **/Gemfile, **/gems.rb
Bundler/OrderedGems:
  Exclude:
    - 'Gemfile'

# Offense count: 1
Lint/RescueException:
  Exclude:
    - 'lib/tasks/scholarsphere.rake'

# Offense count: 2
# Cop supports --auto-correct.
Lint/UnifiedInteger:
  Exclude:
    - 'spec/presenters/error_presenter_spec.rb'

# Offense count: 183
# Configuration parameters: CountComments, ExcludedMethods.
Metrics/BlockLength:
  Max: 226

# Offense count: 38
RSpec/AnyInstance:
  Exclude:
    - 'spec/controllers/batch_edits_controller_spec.rb'
    - 'spec/controllers/catalog_controller_spec.rb'
    - 'spec/controllers/collections_controller_spec.rb'
    - 'spec/controllers/curation_concerns/generic_works_controller_spec.rb'
    - 'spec/controllers/downloads_controller_spec.rb'
    - 'spec/controllers/my/works_controller_spec.rb'
    - 'spec/controllers/zotero_controller_spec.rb'
    - 'spec/features/file_set/analytics_spec.rb'
    - 'spec/features/generic_work/upload_and_delete_spec.rb'
    - 'spec/jobs/share_notify_delete_job_spec.rb'
    - 'spec/jobs/share_notify_job_spec.rb'
    - 'spec/lib/devise/http_header_authenticatable_spec.rb'
    - 'spec/lib/scholarsphere/role_mapper_spec.rb'
    - 'spec/rake/share_notify_spec.rb'
    - 'spec/services/generic_work_to_share_json_service_spec.rb'

# Offense count: 12
RSpec/BeEql:
  Exclude:
    - 'spec/controllers/my/works_controller_spec.rb'
    - 'spec/features/collection/view_and_search_spec.rb'

# Offense count: 2
RSpec/BeforeAfterAll:
  Exclude:
    - 'spec/models/user_mailer_spec.rb'
    - 'spec/services/zotero_subscription_spec.rb'

# Offense count: 83
# Configuration parameters: Max.
RSpec/ExampleLength:
   Max: 10
   Exclude:
     - 'spec/features/**/*'
     - 'spec/lib/scholarsphere/import/work_builder_spec.rb'
     - 'spec/services/field_configurator_spec.rb'
     - 'spec/services/user_stats_importer_spec.rb'

# Offense count: 2
RSpec/ExpectActual:
  Exclude:
    - 'spec/routing/route_spec.rb'
    - 'spec/controllers/sessions_controller_spec.rb'

# Offense count: 6
# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: is_expected, should
RSpec/ImplicitExpect:
  Exclude:
    - 'spec/models/user_spec.rb'

# Offense count: 12
RSpec/LetSetup:
  Exclude:
    - 'spec/features/collection/create_spec.rb'
    - 'spec/features/collection/edit_spec.rb'
    - 'spec/features/dashboard/dashboard_spec.rb'
    - 'spec/features/home_page_spec.rb'
    - 'spec/features/users_spec.rb'
    - 'spec/models/collection_spec.rb'
    - 'spec/models/content_block_spec.rb'

# Offense count: 108
# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: have_received, receive
RSpec/MessageSpies:
  Enabled: false

# Offense count: 201
RSpec/MultipleExpectations:
  Max: 4
  Exclude:
    - 'spec/features/**/*'
    - 'spec/lib/scholarsphere/import/**/*'
    - 'spec/models/resource_filtered_list_spec.rb'
    - 'spec/models/user_mailer_spec.rb'
    - 'spec/models/user_spec.rb'
    - 'spec/presenters/stats_presenter_spec.rb'
    - 'spec/rake/sitemap_spec.rb'
    - 'spec/services/generic_work_list_to_csv_spec.rb'
    - 'spec/views/curations_concerns/base/_form_files.html.erb_spec.rb'
    - 'spec/views/user_mailer/stats_email.html.erb_spec.rb'
    - 'spec/controllers/my/works_controller_spec.rb'
    - 'spec/controllers/zotero_controller_spec.rb'
    - 'spec/jobs/import_url_job_spec.rb'
    - 'spec/jobs/resolrize_job_spec.rb'
    - 'spec/services/user_stats_importer_spec.rb'

# Offense count: 77
RSpec/NamedSubject:
  Exclude:
    - 'spec/presenters/*'
    - 'spec/renderers/*'
    - 'spec/services/*'
    - 'spec/controllers/**/*'
    - 'spec/models/resource_filtered_list_spec.rb'
    - 'spec/models/user_spec.rb'
    - 'spec/models/generic_work_spec.rb'
    - 'spec/lib/hydra/derivatives/document_spec.rb'
    - 'spec/models/public_filtered_list_spec.rb'
    - 'spec/lib/devise/http_header_authenticatable_spec.rb'
    - 'spec/forms/generic_work_form_spec.rb'
    - 'spec/config/google_analytics_spec.rb'

# Offense count: 65
# Configuration parameters: Max.
RSpec/NestedGroups:
  Exclude:
    - 'spec/controllers/admin/stats_controller_spec.rb'
    - 'spec/controllers/downloads_controller_spec.rb'
    - 'spec/controllers/my/works_controller_spec.rb'
    - 'spec/features/generic_work/upload_and_delete_spec.rb'
    - 'spec/features/generic_work/view_and_download_spec.rb'
    - 'spec/indexers/work_indexer_spec.rb'
    - 'spec/jobs/copy_permissions_job_spec.rb'
    - 'spec/jobs/share_notify_job_spec.rb'
    - 'spec/lib/devise/http_header_authenticatable_spec.rb'
    - 'spec/lib/scholarsphere/import/version_builder_spec.rb'
    - 'spec/models/ldap_user_spec.rb'
    - 'spec/models/permissions_change_set_spec.rb'
    - 'spec/models/user_spec.rb'
    - 'spec/rake/scholarsphere/solr_spec.rb'
    - 'spec/views/curations_concerns/base/_items.html.erb_spec.rb'

# Offense count: 5
RSpec/ScatteredLet:
  Exclude:
    - 'spec/controllers/catalog_controller_spec.rb'
    - 'spec/features/dashboard/dashboard_works_spec.rb'

# Offense count: 2
RSpec/ScatteredSetup:
  Exclude:
    - 'spec/lib/hydra/derivatives/document_spec.rb'

# Offense count: 6
RSpec/SubjectStub:
  Exclude:
    - 'spec/controllers/sufia/batch_uploads_controller_spec.rb'
    - 'spec/lib/devise/http_header_authenticatable_spec.rb'
    - 'spec/lib/hydra/derivatives/document_spec.rb'

# Offense count: 20
# Configuration parameters: IgnoreSymbolicNames.
RSpec/VerifiedDoubles:
  Exclude:
    - 'spec/actors/sufia/create_with_remote_files_actor_spec.rb'
    - 'spec/controllers/zotero_controller_spec.rb'
    - 'spec/jobs/attach_files_to_work_job_spec.rb'
    - 'spec/lib/devise/http_header_authenticatable_spec.rb'
    - 'spec/presenters/file_set_presenter_spec.rb'
    - 'spec/rake/share_notify_spec.rb'
    - 'spec/services/permissions_change_service_spec.rb'
    - 'spec/views/my/_sort_and_per_page.html.erb_spec.rb'
    - 'spec/views/users/show.html.erb_spec.rb'

# Offense count: 12
# Cop supports --auto-correct.
Rails/ApplicationJob:
  Exclude:
    - 'app/jobs/batch_create_job.rb'
    - 'app/jobs/copy_permissions_job.rb'
    - 'app/jobs/create_derivatives_job.rb'
    - 'app/jobs/import_url_job.rb'
    - 'app/jobs/import_version_job.rb'
    - 'app/jobs/ingest_file_job.rb'
    - 'app/jobs/ingest_local_file_job.rb'
    - 'app/jobs/rdf_authority_import_job.rb'
    - 'app/jobs/register_queued_file_job.rb'
    - 'app/jobs/resolrize_job.rb'
    - 'app/jobs/share_notify_job.rb'
    - 'app/jobs/sitemap_regenerate_job.rb'

# Offense count: 6
# Cop supports --auto-correct.
Rails/ApplicationRecord:
  Exclude:
    - 'app/models/content_block.rb'
    - 'app/models/qa/local_authority.rb'
    - 'app/models/qa/local_authority_entry.rb'
    - 'app/models/queued_file.rb'
    - 'app/models/trophy.rb'
    - 'app/models/user.rb'

# Offense count: 16
# Cop supports --auto-correct.
# Configuration parameters: Whitelist.
# Whitelist: find_by_sql
Rails/DynamicFindBy:
  Exclude:
    - 'app/actors/curation_concerns/actors/generic_work_actor.rb'
    - 'app/controllers/admin/stats_controller.rb'
    - 'app/jobs/create_derivatives_job.rb'
    - 'app/jobs/import_url_job.rb'
    - 'app/jobs/share_notify_job.rb'
    - 'app/models/user.rb'
    - 'app/services/permissions_change_service.rb'
    - 'lib/devise/strategies/http_header_authenticatable.rb'
    - 'lib/scholarsphere/role_mapper.rb'
    - 'lib/tasks/scholarsphere/users.rake'
    - 'spec/factories/works.rb'
    - 'spec/views/curations_concerns/base/_form_relationships.html.erb_spec.rb'

# Offense count: 27
Rails/FilePath:
  Enabled: false

# Offense count: 32
# Cop supports --auto-correct.
# Configuration parameters: Include.
# Include: spec/**/*, test/**/*
Rails/HttpPositionalArguments:
  Exclude:
    - 'spec/controllers/admin/stats_controller_spec.rb'
    - 'spec/controllers/batch_edits_controller_spec.rb'
    - 'spec/controllers/collections_controller_spec.rb'
    - 'spec/controllers/curation_concerns/generic_works_controller_spec.rb'
    - 'spec/controllers/directory_controller_spec.rb'
    - 'spec/controllers/my/works_controller_spec.rb'
    - 'spec/controllers/qa/terms_controller_spec.rb'
    - 'spec/controllers/sufia/batch_uploads_controller_spec.rb'
    - 'spec/controllers/zotero_controller_spec.rb'

# Offense count: 2
Rails/OutputSafety:
  Exclude:
    - 'app/prepends/prepended_renderers/with_lists.rb'
    - 'app/services/read_only.rb'

# Offense count: 1
# Cop supports --auto-correct.
Rails/PluralizationGrammar:
  Exclude:
    - 'lib/tasks/scholarsphere.rake'

# Offense count: 4
# Configuration parameters: Blacklist.
# Blacklist: decrement!, decrement_counter, increment!, increment_counter, toggle!, touch, update_all, update_attribute, update_column, update_columns, update_counters
Rails/SkipsModelValidations:
  Exclude:
    - 'spec/factories/users.rb'

