---
file_system:
  :home: /Users/cam156/browse-everything/spec/internal
sky_drive:
  :client_id: 0000000040104FCC
  :client_secret: Dlwv6wBb4Ovwbhgncmb7bADu2CfNG9SL
box:
  :client_id: 74nzgjtva34hydx72ob1hnp63mz8a2wu
  :client_secret: l1hZapXgGRLIcLqX5OkHhhf0Jc2o5IXT
drop_box:
  :app_key: k6jb61c2ubew4jq
  :app_secret: 3fkmgikquhyiq6v
google_drive:
  :client_id: "535620292949.apps.googleusercontent.com"
  :client_secret: "RjZV_WDse7KuhnmEpjzjPZjv"


