# Require this file at the top of each feature spec.
require_relative './support/rails'
require_relative './support/capybara'
require_relative './support/poltergeist'
require_relative './support/authentication'
require_relative './support/factories'
require_relative './support/cleanup'
require_relative './support/helpers/fixtures'
require_relative './support/mail'
require_relative './support/helpers/generic_files'
require_relative './support/selectors'
require_relative './support/helpers/collections'
require_relative './support/helpers/ajax'
